name: Build Angular Application

on:
  push:
    branches:
      - deploy
  pull_request:
    branches:
      - deploy

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20 # Use the version your project requires
          cache: 'npm'

      # Step 3: Install dependencies
      - name: Install Dependencies
        run: npm ci

      # Step 4: Build Angular Application
      - name: Build Angular
        run: npm run build -- --prod

      # Step 5: Upload Build Artifacts (Optional)
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: angular-build
          path: dist/ # Ensure this path matches your Angular build output directory
